language: node_js
node_js:
    - "6.2.0"
before_script:
    - npm install
env:
  - NODE_ENV=development
script:
    - npm run build
    - npm run generate:dll
    - npm run regenerate
    - npm run test:coverage
    - npm run coveralls
    - npm run lint:all
notifications:
  slack:
    on_pull_requests: false
    rooms:
      - cejs-atsistemas:XxetFLj7MuJALpcVhx2PKEE6#react-base
