
environment:
  matrix:
    - nodejs_version: 8.9.1

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run build:prod
  - npm run generate:dll
  - npm run test:coverage
  - npm run lint:all
